### ISSUE TITLE
Integrate the Xbox Smartglass REST server

### ISSUE THREAD

**Issue by tgru** [tgru/xbox-control-skill#2]
To ease the installation process the [Xbox Smartglass REST server](https://github.com/OpenXbox/xbox-smartglass-core-python) should be integrated somehow or installed automatically.

**TODO**:
- [ ] Check what is possible with the license of the project (GPLv3)
- [ ] Decide how to integrate under those terms
- [ ] Do the integration
